import { describe, it, expect } from 'vitest';
import { completionSnippetNames, createProxyFromCase } from '../setup';

const { proxy, absolutePath, code } = createProxyFromCase(
	'tests/cases/mixxx-types.ts'
);

describe('Mixxx Types Param Completion Tests', () => {
	it('should suggest all dynamic Mixxx controls', () => {
		const cursorPos = code.indexOf(`getValue('', '')`) + 14;
		const result = proxy.getCompletionsAtPosition(absolutePath, cursorPos, {});

		expect(result).toBeDefined();
		expect(completionSnippetNames(result!)).toStrictEqual([
			'PeakIndicator0',
			'PeakIndicator0_up',
			'PeakIndicator0_down',
			'PeakIndicator0_up_small',
			'PeakIndicator0_down_small',
			'PeakIndicator0_set_one',
			'PeakIndicator0_set_minus_one',
			'PeakIndicator0_set_default',
			'PeakIndicator0_set_zero',
			'PeakIndicator0_toggle',
			'PeakIndicator0_minus_toggle',
			'VuMeter0',
			'VuMeter0_up',
			'VuMeter0_down',
			'VuMeter0_up_small',
			'VuMeter0_down_small',
			'VuMeter0_set_one',
			'VuMeter0_set_minus_one',
			'VuMeter0_set_default',
			'VuMeter0_set_zero',
			'VuMeter0_toggle',
			'VuMeter0_minus_toggle',
			'beatjump_0_backward',
			'beatjump_0_forward',
			'beatloop_0_activate',
			'beatloop_0_enabled',
			'beatloop_0_toggle',
			'beatloop_r0_activate',
			'beatlooproll_0_activate',
			'beatlooproll_r0_activate',
			'hotcue_0_activate',
			'hotcue_0_activatecue',
			'hotcue_0_activateloop',
			'hotcue_0_clear',
			'hotcue_0_color',
			'hotcue_0_cueloop',
			'hotcue_0_goto',
			'hotcue_0_gotoandloop',
			'hotcue_0_gotoandplay',
			'hotcue_0_gotoandstop',
			'hotcue_0_position',
			'hotcue_0_set',
			'hotcue_0_setcue',
			'hotcue_0_setloop',
			'hotcue_0_status',
			'hotcue_0_type',
			'loop_move_0_backward',
			'loop_move_0_forward',
			'group_[Sampler0]_enable',
			'group_[Channel0]_enable',
			'button_parameter0',
			'parameter0',
			'parameter0_up',
			'parameter0_down',
			'parameter0_up_small',
			'parameter0_down_small',
			'parameter0_set_one',
			'parameter0_set_minus_one',
			'parameter0_set_default',
			'parameter0_set_zero',
			'parameter0_toggle',
			'parameter0_minus_toggle',
			'parameter0_link_inverse',
			'parameter0_link_type',
			'button_parameter0_loaded',
			'button_parameter0_type',
			'parameter0_loaded',
			'parameter0_type',
		]);
	});

	it('should suggest dynamic Mixxx controls for [Channel1] group', () => {
		const cursorPos = code.indexOf(`getValue('[Channel1]', '');`) + 24;
		const result = proxy.getCompletionsAtPosition(absolutePath, cursorPos, {});

		expect(result).toBeDefined();
		console.log(completionSnippetNames(result!));
		expect(completionSnippetNames(result!)).toStrictEqual([
			'PeakIndicator0',
			'PeakIndicator0_up',
			'PeakIndicator0_down',
			'PeakIndicator0_up_small',
			'PeakIndicator0_down_small',
			'PeakIndicator0_set_one',
			'PeakIndicator0_set_minus_one',
			'PeakIndicator0_set_default',
			'PeakIndicator0_set_zero',
			'PeakIndicator0_toggle',
			'PeakIndicator0_minus_toggle',
			'VuMeter0',
			'VuMeter0_up',
			'VuMeter0_down',
			'VuMeter0_up_small',
			'VuMeter0_down_small',
			'VuMeter0_set_one',
			'VuMeter0_set_minus_one',
			'VuMeter0_set_default',
			'VuMeter0_set_zero',
			'VuMeter0_toggle',
			'VuMeter0_minus_toggle',
			'beatjump_0_backward',
			'beatjump_0_forward',
			'beatloop_0_activate',
			'beatloop_0_enabled',
			'beatloop_0_toggle',
			'beatloop_r0_activate',
			'beatlooproll_0_activate',
			'beatlooproll_r0_activate',
			'hotcue_0_activate',
			'hotcue_0_activatecue',
			'hotcue_0_activateloop',
			'hotcue_0_clear',
			'hotcue_0_color',
			'hotcue_0_cueloop',
			'hotcue_0_goto',
			'hotcue_0_gotoandloop',
			'hotcue_0_gotoandplay',
			'hotcue_0_gotoandstop',
			'hotcue_0_position',
			'hotcue_0_set',
			'hotcue_0_setcue',
			'hotcue_0_setloop',
			'hotcue_0_status',
			'hotcue_0_type',
			'loop_move_0_backward',
			'loop_move_0_forward',
		]);
	});
});
